### PR TITLE
Lab 7

### PR DESCRIPTION
**Pull request by danylykkk**

### CODE REVIEW

**Review by polyakovartem — CHANGES_REQUESTED** [review]
where is word statistics? What happens if the file size is 10GB

**Comment by danylykkk** [comment]
Could you advise me, where I can find so big text file? Most so big files are binary? And what statistic do you mean? Explain it more precisely. My program returns word count as in task.

**Comment by polyakovartem** [comment]
Hey,

Word stats it’s the wordcount per word. Let say you have the string: “to be or not to be”, so the work stats is:
To: 2
Be: 2
Or: 1
Not: 1
As for big test, I’m sure you can coup with the task of googling the text.

Thanks,
Artem

Artem Polyakov | Consultant, Engineering
GlobalLogic
P +380322448347 M +380913275432  S polyakovartem
www.globallogic.com

http://www.globallogic.com/email_disclaimer.txt

**Review by polyakovartem — CHANGES_REQUESTED** [review]
your approach will not work on large files

**Comment by danylykkk** [comment]
It works fine even for 10 GB

**Review by polyakovartem — CHANGES_REQUESTED** [review]
please do not forget about the word stats

**Comment by danylykkk** [comment]
> please do not forget about the word stats

I didn't forget.
image
image

**Comment by polyakovartem** [comment]
your function should return data structures with words stats, not print the stats, therefore it does nothing useful

**Pull request closed without merging**
